name: Continuous Integration

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  # SimpleCov suggests setting the JRuby --debug flag to ensure that coverage
  # results from JRuby are complete.
  JRUBY_OPTS: --debug

# Tested platforms / Ruby versions:
#  - Ubuntu: MRI (3.1, 3.2, 3.3, 3.4), TruffleRuby (24), JRuby (9.4)
#  - Windows: MRI (3.1)

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.operating-system }}

    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3", "3.4"]
        operating-system: [ubuntu-latest]
        include:
          - ruby: "3.1"
            operating-system: windows-latest
          - ruby: "jruby-9.4"
            operating-system: ubuntu-latest
            env: { FAIL_ON_LOW_COVERAGE: FALSE }
          - ruby: "truffleruby-24"
            operating-system: ubuntu-latest
            env: { FAIL_ON_LOW_COVERAGE: FALSE }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rake
        run: bundle exec rake

  coverage:
    name: Report test coverage to CodeClimate

    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Report test coverage
        uses: paambaati/codeclimate-action@v9
        env:
          CC_TEST_REPORTER_ID: d3bf532dce7cc5d9ae5ae10efd7708d8465d3cc6236e5e11377cbef62ed2b32f
        with:
          coverageCommand: bundle exec rake spec
          coverageLocations: ${{github.workspace}}/coverage/lcov/*.lcov:lcov
