name: Ruby

on:
  push:
    branches:
      - main

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', 'head']

    name: Build on Ruby ${{ matrix.ruby }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rake
        run: bundle exec rake
